---
title: "R Notebook"
output: html_notebook
---

```{r}
require(data.table)
require(ggplot2)
require(table1)
```

# Data from Excel
```{r}

dt2 <- fread("C:/Personal/Luigi/COVID study Master sheet w ELISA data July 2023-2.csv")
dt3 <- fread("C:/Personal/Luigi/COVID study Master sheet w ELISA data July 2023-3.csv")
```

```{r}
dt1 <- fread("C:/Personal/Luigi/COVID study Master sheet w ELISA data July 2023.csv")

dt1 <- dt1[!is.na(AnyDM), ]

dt1$AnyDM <- factor(dt1$AnyDM,
                    levels = c(0, 1),
                    labels = c("DM", "No DM"))
dt1$Sex <- factor(dt1$Sex,
                  levels = c(0, 1),
                  labels = c("0", "1")) # GET LABELS from Lu!
dt1$Race <- factor(dt1$Race,
                   levels = 0:4,
                   labels = c("0", "1", "2", "3", "4")) # GET LABELS from Lu!
dt1$Vaccinated <- factor(dt1$Vaccinated,
                         levels = 0:1,
                         labels = c("Yes", "No"))
dt1$`Dose #1` <- factor(dt1$`Dose #1`,
                        levels = 0:1)
dt1$`Dose #2` <- factor(dt1$`Dose #2`,
                        levels = 0:1)

dt1$LOS <- as.numeric(dt1$LOS)
```

```{r}
table1(~ `Whole Blood` +
         Plasma +
         `Study Group` +
         `Inpatient=1, ER=2, OP=3` +
         Age +
         Sex +
         Race +
         `Height (cm)` +
         `Weight (kg)` +
         BMI +
         `If BMI ?30 Obesity Class (I,II,III)` +
         Vaccinated +
         `Dose #1` +
         `Dose #2` +
         LOS | AnyDM,
       data = dt1)
```

